### ISSUE TITLE
problem in fetching the if from post

### ISSUE THREAD

**Issue by rajatdotgo** [pepperkick/springboot-ems#1]
[x] Test Case 10: Perform POST /employee
Response name should be "Black Panther" but found null
Response body: {"employee":{"id":11,"jobTitle":"Manager","name":"Black Panther"},"manager":{2,"jobTitle":"Manager","name":"Iron Man"},{"id":3,"jobTitle":"Lead","name":"Hulk"}]}

**Comment by pepperkick** [comment]
The response body is not in proper JSON format
```
{
   "employee":{
      "id":11,
      "jobTitle":"Manager",
      "name":"Black Panther"
   },
   "manager":{
      2,
      "jobTitle":"Manager",
      "name":"Iron Man"
   },
{
      "id":3,
      "jobTitle":"Lead",
      "name":"Hulk"
   }
]
}
```

Errors
- manager has ID key missing
- there are no colleagues array

Please fix this and try again.
